config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  resources :admin
  resources :items do
    resources :lineitems
  end 
  resources :carts do
    resources :lineitems
  end 
  resources :orders do
    resources :lineitems
  end
  resources :lineitems
  resources :users
  resources :access
  resources :shopper
    
  resources :aboutus
  resources :contact
  resources :questions
  
  get    '/login',   to: 'access#new'
  post   '/login',   to: 'access#create'
  delete '/logout',  to: 'access#destroy'

  #resources :shopper
  root 'shopper#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    #has_many :lineitems
    has_many :lineitems, dependent: :destroy
    
    def add_item( item_id)     
        current_item = lineitems.find_by(item_id: item_id) 
        if current_item       
            current_item.quantity += 1 
        else      
            current_item = lineitems.build(item_id: item_id) 
        end    
        current_item 
    end
    
    def total_price    
        lineitems.to_a.sum {|item| item.total_price} 
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
    has_many :lineitems
    
    before_destroy :make_sure_no_line_items
    
    validates :name, :description, :image, presence: true  
    validates :price, numericality: {greater_than_or_equal_to: 0.01}   
    validates :name, uniqueness: true  
    validates :image, allow_blank: true, format: {with: %r{\.(gif|jpg|png)\Z}i, message: 'must be GIF, JPG, PNG images'} 
    #SEARCH_TYPES = ["Description", "Name", "Price"]
    
    def make_sure_no_line_items
        if lineitems.empty? 
            returntrue
        else      
            errors.add(:base, 'Line Items present') 
            returnfalse
        end
    end
    
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
    belongs_to :item  
    belongs_to :cart
    belongs_to :order
    
    def total_price    
        item.price * quantity 
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
    has_many :lineitems, dependent: :destroy
    PAYMENT_TYPES = ["Check", "Credit Card", "Venmo", "Paypal"]
    validates :name, :address, :email, presence: true
    validates :paytype, inclusion: PAYMENT_TYPES
    
    def add_items_from_cart(cart)     
        cart.lineitems.each do |item|       
            item.cart_id = nil      
            item.order_id = self.id 
        end 
    end    
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, presence: true, uniqueness: true  
    has_secure_password    
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  include CurrentCart
  before_action :set_cart
  skip_before_action :authorize 
  # GET /welcome
  def index
      @total_orders = Order.count
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

before_action :set_cart, only: [:show, :edit, :update, :destroy]
skip_before_action :authorize    

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy 
    if @cart.id == session[:cart_id]    
        session[:cart_id] = nil    
    end
    respond_to do |format|       
        format.html { redirect_to root_url, notice: 'Your shopping cart is currently empty.' }       
        format.json { head :no_content } 
    end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit()
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    include CurrentCart
    before_action :set_cart
    skip_before_action :authorize 
    
    before_action :set_item, only: [:show, :edit, :update, :destroy]  

    #GET
    def index   
        @items = Item.all
    end
    
    #GET
    def show
        @item = Item.find(params[:id])
    end 
  
    def new 
        @item = Item.new
    end 
  
    def edit
    end 
   
    def create
        @item = Item.new(item_params)

        respond_to do |format|
            if @item.save
                format.html { redirect_to @item, notice: 'Item was successfully created.' }
                format.json { render :show, status: :created, location: @item }
            else
                format.html { render :new }
                format.json { render json: @item.errors, status: :unprocessable_entity }
            end
        end
    end
  
    def update
        respond_to do |format|
            if @item.update(item_params)
                format.html { redirect_to @item, notice: 'Item was successfully updated.' }
                format.json { render :show, status: :ok, location: @item }
            else
                format.html { render :edit }
                format.json { render json: @item.errors, status: :unprocessable_entity }
            end
        end
    end
   
    def destroy
        @item.destroy
        respond_to do |format|
            format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
    
    private
        # Use callbacks to share common setup or constraints between actions.
        def set_item
            @item = Item.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def item_params
            params.require(:item).permit(:name, :description, :image, :price, :term)
        end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/shopper_helper.rb
module ShopperHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/carts/_cart.html.erb
<h4>Cart:</h4>   
<table>
    <% @cart.lineitems.each do |item|%>         
    <tr>
        <td><%= item.quantity %></td>
        <td><%=item.item.name %></td>
        <td class='item_price'><%=number_to_currency(item.item.price) %></td>
    </tr>    
    <%end%>    
    <tr class='total_line'>
        <td colspan = "2">Total</td>
        <td class='total_cell'><%=number_to_currency(@cart.total_price)%></td>
    </tr>   
</table>
<%= button_to 'Check Out', new_order_path, method: :get, class: 'btn btn-success btn-block' %> 
<%= button_to 'Empty Cart', @cart, method: :delete, class: 'btn btn-warning btn-block', data: {confirm: 'Are you sure?'} %> 

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %> 
    <p id="notice"><%= notice %></p>  
<% end %> 
<h3>Items in your shopping cart</h3>   

<table>

    <% @cart.lineitems.each do |item|%>         
    <tr>
        <td><%= item.quantity %></td>
        <td><%=item.item.name %></td>
        <td class='item_price'><%=number_to_currency(item.item.price) %></td>
    </tr>    
    <%end%>    
    <tr class='total_line'>
        <td colspan = "2">Total</td>
        <td class='total_cell'><%=number_to_currency(@cart.total_price)%></td>
    </tr>   
</table>
<%= button_to 'Empty Cart', @cart, method: :delete, data: {confirm: 'Are you sure?'} %> 

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', :required => true %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 10, cols: 50, class: 'form-control', :required => true %>
  </div>
  <div class="field form-group">
    <%= f.label :image %><br>
    <%= f.text_field :image, class: 'form-control', :required => true %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: 'form-control', :required => true, step: :any %>
  </div>
  <div class="actions">
    <%= f.submit 'Save Item', class: 'btn btn-success btn-block' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item Form</h1>
<h2>Here you can edit the item record.</h2>

<%= render 'form' %>

<p></p>
<%= link_to 'Show', @item, class: 'btn btn-warning btn-block'%>
<p></p>
<a class="btn btn-info btn-block" href="/items">Admin Items</a>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
    <h1>Admin Item List</h1>
    <p class="lead">Admin: Here you can add, delete, view and edit items.</p>
    <br>
    <% @items.each do |item| %>   
    <tr class="<%= cycle('list_line_odd', 'list_line_even')%>">     
        <td>       
            <%= image_tag(item.image) %>     
        </td>     
        <td class="list_description">       
            <dl>         
                <dt><%= item.name %></dt>         
                <dd>           
                    <%= item.description %>           
                    <br><br>           
                    <%= item.price %>         
                </dd>       
            </dl>     
        </td>     
        <td class="list_actions">       
            <%= link_to 'Show', item %>       
            <%= link_to 'Edit', edit_item_path(item) %>       
            <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>     
        </td>   
    </tr>   
    <% end %> 
</table> 
<br>
<a href="/items/new"><button class="btn btn-lg btn-primary btn-block" type="submit">Add New Items</button></a>

app/views/items/new.html.erb
<h1>New Item Form</h1>
<h2>Please enter a new item.</h2>

<%= render 'form' %>

app/views/items/show.html.erb
<h2>Item Record: <%= @item.name %></h2>
<div class="field form-group"> 
  <strong>Name:</strong>
  <%= @item.name %>
</div>

<div class="field form-group"> 
  <strong>Description:</strong>
  <%= @item.description %>
</div>

<div class="field form-group"> 
  <strong>Image:</strong>
  <%= @item.image %>
</div>

<div class="field form-group"> 
  <strong>Price:</strong>
  <%= @item.price %>
</div>

<div class="field form-group"> 
  <strong>Created On:</strong>
  <%= @item.created_at %>
</div>

<div class="field form-group"> 
  <strong>Updated On:</strong>
  <%= @item.updated_at %>
</div>
<%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-warning btn-block' %>
<br>
<a class="btn btn-info btn-block" href="/items">Admin Items</a>